### ISSUE TITLE
Update style-dictionary browser patch to latest (3.1.1 -> 3.7.1)

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/style-dictionary-configurator#5]

**Comment by jorenbroekema** [comment]
Note: there's some new formats in Style Dictionary 3.x -> `typescript/module-declarations`. Currently in the browser patch, we handle statements like `fs.readFileSync(__dirname + '/templates/android/resources.template')` by transforming them with Rollup to inline the contents of the templates, but the typescript module declarations is not handled, because it imports a type not from the templates folder. We should add a find+replace statement for this case.
